In [13]:
import pandas as pd
import requests

In [14]:
response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=c4ceb37b72b398db275430f1b2a70899&language=en-US&page=1')

In [15]:
df = pd.DataFrame(response.json()['results'])[
    ['id', 'title', 'overview', 'release_date',
     'popularity', 'vote_average', 'vote_count']
]

In [16]:
df.head()

,id,title,overview,release_date,popularity,vote_average,vote_count
0,1560520,Batman: Knightfall Part 1: Knightfall,"Arkham Asylum has been destroyed, and all its ...",2026-06-23,46.7353,9.104,452
1,980431,Avatar Aang: The Last Airbender,"Avatar Aang, the world's last Airbender, learn...",2026-07-24,78.8718,9.102,1312
2,1007757,Swapped,"A small woodland creature and a majestic bird,...",2026-05-01,45.8570,8.861,2244
3,1632181,Accidental Partners,Two women discover they were both scammed by t...,2026-03-12,17.3276,8.821,396
4,1311031,Demon Slayer: Kimetsu no Yaiba Infinity Castle,The Demon Slayer Corps are drawn into the Infi...,2025-07-18,56.7322,8.800,2280

In [17]:
df=pd.DataFrame()

In [18]:
df

Empty DataFrame
Columns: []
Index: []

In [19]:
for i in range(1, 567):
    response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=c4ceb37b72b398db275430f1b2a70899&language=en-US&page='.format(i))


    temp_df = pd.DataFrame(response.json()['results'])[
        ['id', 'title', 'overview', 'release_date',
         'popularity', 'vote_average', 'vote_count']
    ]

    df = pd.concat([df, temp_df], ignore_index=True)

In [20]:
df

,id,title,overview,release_date,popularity,vote_average,vote_count
0,1560520,Batman: Knightfall Part 1: Knightfall,"Arkham Asylum has been destroyed, and all its ...",2026-06-23,46.7353,9.104,452
1,980431,Avatar Aang: The Last Airbender,"Avatar Aang, the world's last Airbender, learn...",2026-07-24,78.8718,9.102,1312
2,1007757,Swapped,"A small woodland creature and a majestic bird,...",2026-05-01,45.8570,8.861,2244
3,1632181,Accidental Partners,Two women discover they were both scammed by t...,2026-03-12,17.3276,8.821,396
4,1311031,Demon Slayer: Kimetsu no Yaiba Infinity Castle,The Demon Slayer Corps are drawn into the Infi...,2025-07-18,56.7322,8.800,2280
...,...,...,...,...,...,...,...
11315,155,The Dark Knight,Batman raises the stakes in his war on crime. ...,2008-07-16,56.3074,8.500,36957
11316,1218925,Chainsaw Man - The Movie: Reze Arc,"In a brutal war between devils, hunters, and s...",2025-09-19,29.5122,8.538,1240
11317,129,Spirited Away,"A young girl, Chihiro, becomes trapped in a st...",2001-07-20,42.6289,8.536,19037
11318,497,The Green Mile,A supernatural tale set on death row in a Sout...,1999-12-10,35.4577,8.506,19953
11319,122,The Lord of the Rings: The Return of the King,As armies mass for a final battle that will de...,2003-12-17,40.7323,8.504,27565

In [21]:
df.shape

(11320, 7)